//PRODUCT
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";
export const GET_INFO_PRODUCTS = "GET_INFO_PRODUCTS";
export const SEARCH_PRODUCT_ITEM = "SEARCH_PRODUCT_ITEM";

//CATEGORY
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS =
  "GET_PRODUCTS_BY_CATEGORY_SUCCESS";
export const GET_PRODUCTS_BY_CATEGORY_FAILURE =
  "GET_PRODUCTS_BY_CATEGORY_FAILURE";

//CART
export const REMOVE_ALL_PRODUCTS = "REMOVE_ALL_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PAY_PRODUCT = "PAY_PRODUCT";
export const PAY_PRODUCT_SUCCESS = "PAY_PRODUCT_SUCCESS";
export const PAY_PRODUCT_FAILURE = "PAY_PRODUCT_FAILURE";
export const PAY_ALL_PRODUCTS = "PAY_ALL_PRODUCTS";
export const PAY_ALL_PRODUCTS_SUCCESS = "PAY_ALL_PRODUCTS_SUCCESS";
export const PAY_ALL_PRODUCTS_FAILURE = "PAY_ALL_PRODUCTS_FAILURE";
export const CONFIRM_PAYMENT = "CONFIRM_PAYMENT";
export const CONFIRM_PAYMENT_SUCCESS = "CONFIRM_PAYMENT_SUCCESS";
export const CONFIRM_PAYMENT_FAILURE = "CONFIRM_PAYMENT_FAILURE";
export const UPDATE_CART_PRODUCT = "UPDATE_CART_PRODUCT";
export const GET_ALL_BILLS = "GET_ALL_BILLS";
export const GET_PRODUCTS_BILL = "GET_PRODUCTS_BILL";
export const GET_STATE_BILLS = "GET_STATE_BILLS";
export const REMOVE_BILLS = "REMOVE_BILLS";
